### ISSUE TITLE
COMP: CMake Error in linking to target "Threads: Threads"

### ISSUE THREAD

**Issue by yidu-bjcancer** [RTKConsortium/RTK#314]
After generate projects in CMake, a lot of CMake Error showed up and all of them pointed to the same linking problem with "Threads::Threads".

OS: Win10
VS: 2017
Cuda: v10.1
Compilation: x64
```

CMake Error at Modules/Remote/RTK/utilities/ITKCudaCommon/src/CMakeLists.txt:11 (add_library):
  Target "ITKCudaCommon" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/utilities/ITKCudaCommon/src/CMakeLists.txt:11 (add_library):
  Target "ITKCudaCommon" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/utilities/ITKCudaCommon/src/CMakeLists.txt:11 (add_library):
  Target "ITKCudaCommon" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/utilities/ITKCudaCommon/src/CMakeLists.txt:11 (add_library):
  Target "ITKCudaCommon" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at CMake/ITKModuleMacros.cmake:469 (add_library):
  Target "RTK" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Modules/Remote/RTK/src/CMakeLists.txt:139 (itk_module_add_library)


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkamsterdamshroud/CMakeLists.txt:2 (add_executable):
  Target "rtkamsterdamshroud" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkbackprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkbackprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfdk" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfdktwodweights/CMakeLists.txt:2 (add_executable):
  Target "rtkfdktwodweights" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfieldofview/CMakeLists.txt:2 (add_executable):
  Target "rtkfieldofview" links to target "Threads::Threads" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkforwardprojections/CMakeLists.txt:2 (add_executable):
  Target "rtkforwardprojections" links to target "Threads::Threads" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at Modules/Remote/RTK/applications/rtkfourdfdk/CMakeLists.txt:2 (add_executable):
  Target "rtkfourdfdk" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by prawinms** [comment]
Hi, I'm getting the same error while building the ITK using Cuda support. did anybody have any idea how to resolve it

**Comment by SimonRit** [comment]
Do you still have this issue now that #313 is fixed?

**Comment by SimonRit** [comment]
I think this is the same as InsightSoftwareConsortium/ITK#1502 and it has been fixed by InsightSoftwareConsortium/ITK#1503.

**Comment by yidu-bjcancer** [comment]
Sorry for this later reply, Simon. @SimonRit 
I still have this problem today, with the newly downloaded codes.

**Comment by SimonRit** [comment]
Ok, thanks for the report. Have you updated both ITK and RTK?

**Comment by yidu-bjcancer** [comment]
> Ok, thanks for the report. Have you updated both ITK and RTK?

I just downloaded ITK, and tick "Module_RTK" option in CMake. I think RTK will automatically download the updated RTK.

Do I need to download the updated RTK manually?

**Comment by SimonRit** [comment]
This will download the version in [RTK.remote.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Remote/RTK.remote.cmake). You can modify this file and set `GIT_TAG` to `master` if you'd like the latest version. This is however not the problem here.
Can you try disabling `BUILD_TESTING` to see if that helps? According to InsightSoftwareConsortium/ITK#1503, it seems to be a problem related to gtest.

**Comment by yidu-bjcancer** [comment]
No. That doesn't help. The Threads errors are still there.

**Comment by SimonRit** [comment]
I'm not sure to what's the problem here. Do you have google test installed on your computer?

**Comment by yidu-bjcancer** [comment]
No. I don't google test. 
It's weird that I successfully installed RTK on Ubuntu 18.04, but failed on Win10.

**Comment by kabcode** [comment]
I encounter the same problem with a new clone from ITK and RTK using the same configuration but Visual Studio 2019. No google test installed.

**Comment by SimonRit** [comment]
Sorry, I'm a bit far from a Windows computer nowadays. Can someone try the latest cmake v3.17.1? I have noticed this [patch](https://github.com/Kitware/CMake/commit/b9d67447c35681ccf272ec1744cb3208aa2745ba#diff-4740178b5defb85b802090e7f04ae7e2) which might help.

**Comment by kabcode** [comment]
Updating cmake resolves the issue. 
Additional note: Another issue may surface while building that is discussed here: [Fatal errors C1083 and LNK1181 when using RTK module](https://discourse.itk.org/t/fatal-errors-c1083-and-lnk1181-when-using-rtk-module/2951/3)

**Comment by SimonRit** [comment]
Thanks a lot for the update. I consider this is not an RTK problem and there is a cmake solution so issue closed. Let me know if you disagree!
